// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwmhbzndndlqlrfncxbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3bWhiem5kbmRscWxyZm5jeGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjg2MjYsImV4cCI6MjA1OTYwNDYyNn0.T2O-Q4qCAw8xXfNQfcl0BeXZozsfajRz3hDZM5eGq8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);